# This file was generated by GoReleaser. DO NOT EDIT.
class Tparallel < Formula
  desc "tparallel detects inappropriate usage of t.Parallel() method in your Go test codes"
  homepage "https://github.com/moricho/tparallel"
  version "0.2.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moricho/tparallel/releases/download/v0.2.1/tparallel_darwin_x86_64.tar.gz"
    sha256 "e7dcd775994822a4bbff96724be5d8be72f7d826a526ae339df732dafb0a575c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/moricho/tparallel/releases/download/v0.2.1/tparallel_linux_x86_64.tar.gz"
      sha256 "ebb91bba3c5ff5f03229da49e163b91f74988432d52c6caca1f191c7de7dd3ba"
    end
  end

  def install
    bin.install "tparallel"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
