# This file was generated by GoReleaser. DO NOT EDIT.
class Tparallel < Formula
  desc "tparallel detects inappropriate usage of t.Parallel() method in your Go test codes"
  homepage "https://github.com/moricho/tparallel"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/moricho/tparallel/releases/download/v0.1.0/tparallel_darwin_x86_64.tar.gz"
    sha256 "ba01a0af355da642a06cfb5e1efa49369a918351b8c4a51952ed9949b5fe1a02"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/moricho/tparallel/releases/download/v0.1.0/tparallel_linux_x86_64.tar.gz"
      sha256 "d233696c70ecb58b0760baf720299509ef776eba58ff55f1b102bdb156746f59"
    end
  end

  def install
    bin.install "tparallel"
  end

  test do
    system "#{bin}/goreleaser -v"
  end
end
